import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { load as parseYaml } from "js-yaml";
import { siteConfigSchema } from "../schemas/site-config.ts";

// The HSTS settings the user asked to control via site.config.yaml live in
// content/, but nginx.conf is a static file nginx reads at container
// startup — this script is the bridge, run during the Docker build so the
// two never drift out of sync (see docker/Dockerfile).

const ROOT = resolve(import.meta.dirname, "..");
// Overridable so scripts/rebuild-site.ts can write straight to the path
// nginx actually reads at runtime (/etc/nginx/security-headers.conf) when
// content/site.config.yaml changes live, instead of the build-time default.
const OUT_FILE = process.env.NGINX_SECURITY_HEADERS_OUT
  ? resolve(process.env.NGINX_SECURITY_HEADERS_OUT)
  : join(ROOT, "docker/generated/security-headers.conf");

function main() {
  const config = siteConfigSchema.parse(
    parseYaml(readFileSync(join(ROOT, "content/site.config.yaml"), "utf-8")),
  );

  const { hsts } = config.security;
  const hstsHeader = hsts.enabled
    ? `add_header Strict-Transport-Security "max-age=${hsts.maxAgeSeconds}${hsts.includeSubDomains ? "; includeSubDomains" : ""}; preload" always;`
    : "# HSTS disabled in content/site.config.yaml";

  const contents = [
    "# AUTO-GENERATED by scripts/build-nginx-config.ts from content/site.config.yaml — do not edit directly.",
    hstsHeader,
    "",
  ].join("\n");

  mkdirSync(dirname(OUT_FILE), { recursive: true });
  writeFileSync(OUT_FILE, contents);
  console.log(`Wrote ${OUT_FILE} from site.config.yaml`);
}

main();
