import {
  mkdirSync,
  readFileSync,
  readdirSync,
  existsSync,
  writeFileSync,
  rmSync,
} from "node:fs";
import { basename, join, resolve } from "node:path";
import { load as parseYaml } from "js-yaml";
import matter from "gray-matter";
import type { z } from "zod";
import { md } from "./markdown.ts";
import { parseYoutubeId } from "./youtube.ts";
import { siteConfigSchema } from "../schemas/site-config.ts";
import { skillsSchema } from "../schemas/skill.ts";
import { educationSchema } from "../schemas/education.ts";
import { experienceSchema } from "../schemas/experience.ts";
import { credentialsSchema } from "../schemas/credentials.ts";
import { volunteerSchema } from "../schemas/volunteer.ts";
import { languagesSchema } from "../schemas/language.ts";
import { projectFrontmatterSchema, type Project } from "../schemas/project.ts";
import { linksSchema } from "../schemas/link.ts";
import { socialSchema } from "../schemas/social.ts";
import { hobbiesSchema, type Hobby } from "../schemas/hobby.ts";
import { devlogFrontmatterSchema, type DevlogEntry } from "../schemas/devlog.ts";
import { homeSchema, type Home } from "../schemas/home.ts";
import { contactSchema } from "../schemas/contact.ts";
import type { Summary } from "../schemas/summary.ts";

const ROOT = resolve(import.meta.dirname, "..");
const CONTENT_DIR = join(ROOT, "content");
const OUT_DIR = join(ROOT, "src/generated");
const README_CACHE_FILE = join(CONTENT_DIR, ".cache/github-readmes.json");

// `Input = any` (rather than the default `Input = Output`) so T is inferred
// purely from the schema's output side — otherwise fields with `.default()`
// (whose input type is optional) pollute inference and T comes out with
// those fields optional too, even though the parsed output always has them.
/** Required content files must exist — this is the one message users see when they don't. */
function requireContentFile(relativePath: string): string {
  const fullPath = join(CONTENT_DIR, relativePath);
  if (!existsSync(fullPath)) {
    throw new Error(
      `You are missing a file: ${relativePath}. Add ${basename(relativePath)} at this location with the same format as the example file found in the repository`,
    );
  }
  return fullPath;
}

function readYamlFile<T>(
  relativePath: string,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- see comment above: Input is intentionally untyped
  schema: z.ZodType<T, z.ZodTypeDef, any>,
): T {
  const fullPath = requireContentFile(relativePath);
  const raw = parseYaml(readFileSync(fullPath, "utf-8"));
  const result = schema.safeParse(raw);
  if (!result.success) {
    throw new Error(
      `Invalid content in ${relativePath}:\n${result.error.issues
        .map((issue) => `  - ${issue.path.join(".")}: ${issue.message}`)
        .join("\n")}`,
    );
  }
  return result.data;
}

function readMarkdownFile(fullPath: string) {
  return matter(readFileSync(fullPath, "utf-8"));
}

/** Like readMarkdownFile, but for required top-level files (not ones already discovered via readdirSync). */
function readRequiredMarkdownFile(relativePath: string) {
  return readMarkdownFile(requireContentFile(relativePath));
}

function writeGenerated(filename: string, banner: string, body: string) {
  writeFileSync(join(OUT_DIR, filename), `${banner}\n\n${body}\n`);
}

const GENERATED_BANNER =
  "// AUTO-GENERATED by scripts/build-content.ts — do not edit directly.\n// Edit the corresponding file(s) under content/ instead, then rebuild.";

function buildSiteConfig() {
  const config = readYamlFile("site.config.yaml", siteConfigSchema);
  writeGenerated(
    "site-config.ts",
    GENERATED_BANNER,
    `import type { SiteConfig } from '../../schemas/site-config.ts'\n\nexport const siteConfig: SiteConfig = ${JSON.stringify(config, null, 2)}\n`,
  );
}

function buildAbout() {
  const summaryFile = readRequiredMarkdownFile("about/summary.md");
  const summary: Summary = {
    name: String(summaryFile.data.name ?? ""),
    title: String(summaryFile.data.title ?? ""),
    bodyHtml: md.render(summaryFile.content),
  };

  const skills = readYamlFile("about/skills.yaml", skillsSchema);
  const education = readYamlFile("about/education.yaml", educationSchema);
  const experience = readYamlFile("about/experience.yaml", experienceSchema);
  const credentials = readYamlFile("about/credentials.yaml", credentialsSchema);
  const volunteer = readYamlFile("about/volunteer.yaml", volunteerSchema);
  const languages = readYamlFile("about/languages.yaml", languagesSchema);

  writeGenerated(
    "about.ts",
    GENERATED_BANNER,
    [
      `import type { Summary } from '../../schemas/summary.ts'`,
      `import type { Skill } from '../../schemas/skill.ts'`,
      `import type { EducationEntry } from '../../schemas/education.ts'`,
      `import type { ExperienceEntry } from '../../schemas/experience.ts'`,
      `import type { CredentialEntry } from '../../schemas/credentials.ts'`,
      `import type { VolunteerEntry } from '../../schemas/volunteer.ts'`,
      `import type { LanguageEntry } from '../../schemas/language.ts'`,
      "",
      `export const summary: Summary = ${JSON.stringify(summary, null, 2)}`,
      `export const skills: Skill[] = ${JSON.stringify(skills, null, 2)}`,
      `export const education: EducationEntry[] = ${JSON.stringify(education, null, 2)}`,
      `export const experience: ExperienceEntry[] = ${JSON.stringify(experience, null, 2)}`,
      `export const credentials: CredentialEntry[] = ${JSON.stringify(credentials, null, 2)}`,
      `export const volunteer: VolunteerEntry[] = ${JSON.stringify(volunteer, null, 2)}`,
      `export const languages: LanguageEntry[] = ${JSON.stringify(languages, null, 2)}`,
    ].join("\n\n"),
  );
}

function buildHomeLanding() {
  const homeFile = readRequiredMarkdownFile("home.md");
  const result = homeSchema.safeParse(homeFile.data);
  if (!result.success) {
    throw new Error(
      `Invalid frontmatter in home.md:\n${result.error.issues
        .map((issue) => `  - ${issue.path.join(".")}: ${issue.message}`)
        .join("\n")}`,
    );
  }
  const home: Home = {
    ...result.data,
    bodyHtml: md.render(homeFile.content),
  };

  writeGenerated(
    "home.ts",
    GENERATED_BANNER,
    `import type { Home } from '../../schemas/home.ts'\n\nexport const home: Home = ${JSON.stringify(home, null, 2)}\n`,
  );
}

function buildContact() {
  const contact = readYamlFile("contact.yaml", contactSchema);
  writeGenerated(
    "contact.ts",
    GENERATED_BANNER,
    `import type { Contact } from '../../schemas/contact.ts'\n\nexport const contact: Contact = ${JSON.stringify(contact, null, 2)}\n`,
  );
}

/** Parses every devlog file under `content/projects/devlogs/<slug>/`, newest first. */
function readDevlogs(slug: string): DevlogEntry[] {
  const dir = join(CONTENT_DIR, "projects/devlogs", slug);
  const files = existsSync(dir)
    ? readdirSync(dir).filter((f) => f.endsWith(".md"))
    : [];

  const entries: DevlogEntry[] = files.map((file) => {
    // Filenames are date-prefixed, e.g. 2026-02-10-update-title.md
    const dateMatch = file.match(/^(\d{4}-\d{2}-\d{2})-/);
    if (!dateMatch) {
      throw new Error(
        `Devlog file ${slug}/${file} must be named YYYY-MM-DD-<slug>.md`,
      );
    }
    const { data, content } = readMarkdownFile(join(dir, file));
    const result = devlogFrontmatterSchema.safeParse(data);
    if (!result.success) {
      throw new Error(
        `Invalid frontmatter in projects/devlogs/${slug}/${file}:\n${result.error.issues
          .map((issue) => `  - ${issue.path.join(".")}: ${issue.message}`)
          .join("\n")}`,
      );
    }
    const plainText = content.replace(/[#*_`>[\]()]/g, "").trim();
    return {
      ...result.data,
      date: dateMatch[1],
      bodyHtml: md.render(content),
      excerpt:
        plainText.length > 160 ? `${plainText.slice(0, 160)}…` : plainText,
      videoId: result.data.video ? parseYoutubeId(result.data.video) : null,
    };
  });

  entries.sort((a, b) => (a.date < b.date ? 1 : -1)); // newest first
  return entries;
}

function buildProjects() {
  const dir = join(CONTENT_DIR, "projects");
  const files = existsSync(dir)
    ? readdirSync(dir).filter((f) => f.endsWith(".md"))
    : [];

  let readmeCache: Record<
    string,
    { description: string; htmlUrl: string; stars: number; readmeHtml: string }
  > = {};
  if (existsSync(README_CACHE_FILE)) {
    readmeCache = JSON.parse(readFileSync(README_CACHE_FILE, "utf-8"));
  }

  const devlogsBySlug: Record<string, DevlogEntry[]> = {};

  const projects: Project[] = files.map((file) => {
    const slug = file.replace(/\.md$/, "");
    const { data, content } = readMarkdownFile(join(dir, file));
    const result = projectFrontmatterSchema.safeParse(data);
    if (!result.success) {
      throw new Error(
        `Invalid frontmatter in projects/${file}:\n${result.error.issues
          .map((issue) => `  - ${issue.path.join(".")}: ${issue.message}`)
          .join("\n")}`,
      );
    }
    const frontmatter = result.data;

    let bodyHtml: string;
    let stars: number | null;
    let repoUrl = frontmatter.repoUrl;
    if (frontmatter.repo) {
      const key = `${frontmatter.repo.owner}/${frontmatter.repo.repo}`;
      const cached = readmeCache[key];
      if (!cached && process.env.NODE_ENV !== "test") {
        console.warn(
          `No cached data for ${key} — run "npm run fetch:github" before building. Using placeholder.`,
        );
      }
      bodyHtml =
        cached?.readmeHtml ??
        "<p><em>README unavailable — run npm run fetch:github.</em></p>";
      stars = cached?.stars ?? 0;
      repoUrl = cached?.htmlUrl ?? `https://github.com/${key}`;
    } else {
      bodyHtml = md.render(content);
      stars = null;
    }

    const devlogs = readDevlogs(slug);
    devlogsBySlug[slug] = devlogs;

    return {
      ...frontmatter,
      slug,
      bodyHtml,
      stars,
      repoUrl,
      videoId: frontmatter.videoUrl ? parseYoutubeId(frontmatter.videoUrl) : null,
      latestDevlog: devlogs[0] ?? null,
    };
  });

  projects.sort((a, b) => a.order - b.order);

  writeGenerated(
    "projects.ts",
    GENERATED_BANNER,
    `import type { Project } from '../../schemas/project.ts'\n\nexport const projects: Project[] = ${JSON.stringify(projects, null, 2)}\n`,
  );

  writeGenerated(
    "devlogs.ts",
    GENERATED_BANNER,
    `import type { DevlogEntry } from '../../schemas/devlog.ts'\n\nexport const devlogsBySlug: Record<string, DevlogEntry[]> = ${JSON.stringify(devlogsBySlug, null, 2)}\n`,
  );
}

function buildLinks() {
  const links = readYamlFile("links/links.yaml", linksSchema);
  writeGenerated(
    "links.ts",
    GENERATED_BANNER,
    `import type { LinkEntry } from '../../schemas/link.ts'\n\nexport const links: LinkEntry[] = ${JSON.stringify(links, null, 2)}\n`,
  );
}

function buildSocial() {
  const socialLinks = readYamlFile("social/social.yaml", socialSchema);
  writeGenerated(
    "social.ts",
    GENERATED_BANNER,
    `import type { SocialEntry } from '../../schemas/social.ts'\n\nexport const socialLinks: SocialEntry[] = ${JSON.stringify(socialLinks, null, 2)}\n`,
  );
}

function buildHobbies() {
  const hobbyEntries = readYamlFile("hobbies/hobbies.yaml", hobbiesSchema);
  const hobbiesDir = join(CONTENT_DIR, "hobbies");

  const hobbies: Hobby[] = hobbyEntries.map((hobby) => {
    const bodyFile = join(hobbiesDir, `${hobby.id}.md`);
    const bodyHtml = existsSync(bodyFile)
      ? md.render(readMarkdownFile(bodyFile).content)
      : null;
    return { ...hobby, bodyHtml };
  });

  writeGenerated(
    "hobbies.ts",
    GENERATED_BANNER,
    `import type { Hobby } from '../../schemas/hobby.ts'\n\nexport const hobbies: Hobby[] = ${JSON.stringify(hobbies, null, 2)}\n`,
  );
}

function main() {
  rmSync(OUT_DIR, { recursive: true, force: true });
  mkdirSync(OUT_DIR, { recursive: true });

  buildSiteConfig();
  buildAbout();
  buildHomeLanding();
  buildContact();
  buildProjects();
  buildLinks();
  buildSocial();
  buildHobbies();

  console.log("Content pipeline: generated src/generated/*.ts from content/");
}

try {
  main();
} catch (err) {
  // Thrown as a plain Error with a message already formatted for humans
  // (see readYamlFile / readMarkdownFile above) — print just that instead
  // of letting Node dump the raw stack trace, so the reason a content edit
  // failed to publish is the first thing visible in watch-content.ts's log
  // output rather than being buried under internal frames.
  console.error(`Content pipeline failed:\n${err instanceof Error ? err.message : err}`);
  process.exit(1);
}
